---
 - name: Install aptitude using apt
   become: true
   apt:
      name: aptitude
      state: latest
      update_cache: yes
      force_apt_get: true

 - name: Update and upgrade apt packages
   become: true
   apt:
    upgrade: "yes"
    update_cache: "yes"
    cache_valid_time: "86400"

 - name: Install required packages
   become: true
   apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: yes
   with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python3-pip

 - name: Import Docker CE repository gpg key
   become: true
   apt_key:
      url: "{{ docker_key_url }}"
      state: present

 - name: Add Docker CE repository
   become: true
   apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

 - name: Install Docker CE
   become: true
   apt:
    name: docker-ce
    state: present
    update_cache: yes

 - name: Install docker-compose
   become: true
   get_url:
    url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

 - name: Install Docker Module for Python
   become: yes
   pip:
    name:
     - docker
     - docker-compose




 
  

